<?php

/**
 * For testing purposes, comment out for production.
 */
function installer_glue_form_alter(&$form, &$form_state, $form_id) {
  dsm($form_id);  // print form ID to messages
  dsm($form);  // pretty print array using Krumo to messages
}


function installer_glue_form_mh_seller_node_form_alter(&$form, &$form_state, $form_id) {
  $form['field_mh_seller_mh_unit']['und']['actions']['ief_add']['#value'] = array(
    '#title' => t('Create new mh unit'),
  );
  
  $form['field_mh_seller_mh_unit']['und']['actions']['ief_add_existing']['#value'] = array(
    '#title' => t('Add existing mh unit'),
  );
  
  $form['field_mh_seller_contact_info']['und']['actions']['ief_add']['#value'] = array(
    '#title' => t('Create new contact'),
  );
  
  $form['field_mh_seller_contact_info']['und']['actions']['ief_add_existing']['#value'] = array(
    '#title' => t('Add existing contact'),
  );
}


