<?php


/**
 * Implements hook_menu_alter().
 * Alter the data being saved to the {menu_router} table after hook_menu is invoked.
 */
function glue_menu_alter(&$items) {
}

/**
 * Implements hook_entity_info_alter().
 */
function glue_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['short'] = array(
    'label' => t('Short'),
    'custom settings' => TRUE,
  );
}




/**
 * Implements hook_form_alter().
 */
function glue_form_alter(&$form, &$form_state, $form_id) {
  $form['field_mh_unit_shed']['#collapsible'] = TRUE;
}

/**
 * Implements hook_views_pre_render().
 */
function glue_views_pre_render(&$view) {
  rules_invoke_event('glue_event_view_render', $view->name);
  
}
