<?php


/**
 * Implements hook_menu_alter().
 * Alter the data being saved to the {menu_router} table after hook_menu is invoked.
 */
function glue_menu_alter(&$items) {
}

/**
 * Implements hook_entity_info_alter().
 */
function glue_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['short'] = array(
    'label' => t('Short'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_form_alter().
 */
function glue_form_alter(&$form, &$form_state, $form_id) {
  //$form_state['input']['field_mhc_lot_width_3_value'] -= '5';
  //dsm($form);
  //dsm($form_state);
  //dsm($form_id);
}

/**
 * Implements hook_views_pre_render().
 */
function glue_views_pre_render(&$view) {
  rules_invoke_event('glue_event_view_render', $view->name);
  //dsm($view);
  
  
}

/**
 * Impements template_preprocess_views_view_table
 */
function glue_preprocess_views_view_table(&$vars) {
  $view = $vars['view'];  
  
  if ($view->name == 'vacant_lots' && $view->current_display == 'panel_pane_table_list') {
    drupal_add_css(drupal_get_path('module', 'glue') . '/css/glue.css');
    $num_results = count($vars['result']);
    // Adds a class of 'warning-length' if the restricted buildable length of 
    // the lot is shorter than the total buildable length of the lot.
      for ($i=0; $i<$num_results; $i++) {
        $length = $view->result[$i]->field_field_mhc_lot_build_length_2[0]['raw']['value'];
        $length_restricted = $view->result[$i]->field_field_mhc_lot_build_length[0]['raw']['value'];
          if ($length_restricted < $length) {
          $vars['field_classes']['field_mhc_lot_build_length_2'][$i] .= ' warning-length';
        }
      }
  }
  //dsm($vars);
  //dsm($num_results);
}

/**
 * Implements hook_views_api().
 */
function glue_views_api() {
  return array(
    'api' => 3,   
  );
}

/**
 * Implements hook_views_default_views().
 * @return array a list of views
 */
function glue_views_default_views() {
  // Get exported view files.
  // Do not place view code here, instead create a file in /views and name
  // it as such: [viewname].view.inc and the code it contains will automatically
  // be added to the $views array below.
  $module_path = drupal_get_path('module', 'glue');
  $files = file_scan_directory($module_path . '/views', '/.inc/');
 
  $views = array();
 
  foreach ($files as $file_path => $file) {
    require $file_path;
 
    if (isset($view)) {
      $views[$view->name] = $view;
    }
  }
 
  return $views;
}
/*
function glue_views_query_alter(&$view, &$query) {
  if ($view->name == 'vacant_lots') {
    $conditions = $query->where[1]['conditions'];
    foreach ($conditions as $condition) {
      dsm($condition, 'condition');
      if ($condition['field'] == 'field_data_field_mhc_lot_width_3.field_mhc_lot_width_3_value') {
        $condition['value'] -= .5;
      }
    }
    $query->where[1]['conditions'][3]['value'] -= .5;
    //dsm($view);
    dsm($query);
    //dsm($condition, 'condition');
  }
}
*/

/**
 * Implements hook_ctools_plugin_directory().
 */
function glue_ctools_plugin_directory($module, $plugin) {
  if ($module == 'panels' && $plugin == 'layouts') {
    return 'panels/plugins/layouts';
  }
}

